# PostgreSQL database configuration
# All environments use PostgreSQL

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    host: <%= ENV.fetch("TAILVIEW_POSTGRES_HOST", "localhost") %>
    port: <%= ENV.fetch("TAILVIEW_POSTGRES_PORT", "5432") %>
    database: <%= ENV.fetch("TAILVIEW_POSTGRES_DEV_DB", "tailview_development") %>
    username: <%= ENV.fetch("TAILVIEW_POSTGRES_USER", "postgres") %>
    password: <%= ENV.fetch("TAILVIEW_POSTGRES_PASSWORD", "") %>
  cache:
    <<: *default
    host: <%= ENV.fetch("TAILVIEW_POSTGRES_HOST", "localhost") %>
    port: <%= ENV.fetch("TAILVIEW_POSTGRES_PORT", "5432") %>
    database: <%= ENV.fetch("TAILVIEW_POSTGRES_DEV_DB", "tailview_development") %>_cache
    username: <%= ENV.fetch("TAILVIEW_POSTGRES_USER", "postgres") %>
    password: <%= ENV.fetch("TAILVIEW_POSTGRES_PASSWORD", "") %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    host: <%= ENV.fetch("TAILVIEW_POSTGRES_HOST", "localhost") %>
    port: <%= ENV.fetch("TAILVIEW_POSTGRES_PORT", "5432") %>
    database: <%= ENV.fetch("TAILVIEW_POSTGRES_DEV_DB", "tailview_development") %>_queue
    username: <%= ENV.fetch("TAILVIEW_POSTGRES_USER", "postgres") %>
    password: <%= ENV.fetch("TAILVIEW_POSTGRES_PASSWORD", "") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    host: <%= ENV.fetch("TAILVIEW_POSTGRES_HOST", "localhost") %>
    port: <%= ENV.fetch("TAILVIEW_POSTGRES_PORT", "5432") %>
    database: <%= ENV.fetch("TAILVIEW_POSTGRES_DEV_DB", "tailview_development") %>_cable
    username: <%= ENV.fetch("TAILVIEW_POSTGRES_USER", "postgres") %>
    password: <%= ENV.fetch("TAILVIEW_POSTGRES_PASSWORD", "") %>
    migrations_paths: db/cable_migrate

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  primary:
    <<: *default
    host: <%= ENV.fetch("TAILVIEW_POSTGRES_HOST", "localhost") %>
    port: <%= ENV.fetch("TAILVIEW_POSTGRES_PORT", "5432") %>
    database: <%= ENV.fetch("TAILVIEW_POSTGRES_TEST_DB", "tailview_test") %>
    username: <%= ENV.fetch("TAILVIEW_POSTGRES_USER", "postgres") %>
    password: <%= ENV.fetch("TAILVIEW_POSTGRES_PASSWORD", "") %>
  cache:
    <<: *default
    host: <%= ENV.fetch("TAILVIEW_POSTGRES_HOST", "localhost") %>
    port: <%= ENV.fetch("TAILVIEW_POSTGRES_PORT", "5432") %>
    database: <%= ENV.fetch("TAILVIEW_POSTGRES_TEST_DB", "tailview_test") %>_cache
    username: <%= ENV.fetch("TAILVIEW_POSTGRES_USER", "postgres") %>
    password: <%= ENV.fetch("TAILVIEW_POSTGRES_PASSWORD", "") %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    host: <%= ENV.fetch("TAILVIEW_POSTGRES_HOST", "localhost") %>
    port: <%= ENV.fetch("TAILVIEW_POSTGRES_PORT", "5432") %>
    database: <%= ENV.fetch("TAILVIEW_POSTGRES_TEST_DB", "tailview_test") %>_queue
    username: <%= ENV.fetch("TAILVIEW_POSTGRES_USER", "postgres") %>
    password: <%= ENV.fetch("TAILVIEW_POSTGRES_PASSWORD", "") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    host: <%= ENV.fetch("TAILVIEW_POSTGRES_HOST", "localhost") %>
    port: <%= ENV.fetch("TAILVIEW_POSTGRES_PORT", "5432") %>
    database: <%= ENV.fetch("TAILVIEW_POSTGRES_TEST_DB", "tailview_test") %>_cable
    username: <%= ENV.fetch("TAILVIEW_POSTGRES_USER", "postgres") %>
    password: <%= ENV.fetch("TAILVIEW_POSTGRES_PASSWORD", "") %>
    migrations_paths: db/cable_migrate

# Production database configuration
production:
  primary:
    <<: *default
    host: <%= ENV.fetch("TAILVIEW_POSTGRES_HOST", "tailview_postgres") %>
    port: <%= ENV.fetch("TAILVIEW_POSTGRES_PORT", "5432") %>
    database: <%= ENV.fetch("TAILVIEW_POSTGRES_DB", "tailview_production") %>
    username: <%= ENV.fetch("TAILVIEW_POSTGRES_USER", "tailview_user") %>
    password: <%= ENV.fetch("TAILVIEW_POSTGRES_PASSWORD", "") %>
  cache:
    <<: *default
    host: <%= ENV.fetch("TAILVIEW_POSTGRES_HOST", "tailview_postgres") %>
    port: <%= ENV.fetch("TAILVIEW_POSTGRES_PORT", "5432") %>
    database: <%= ENV.fetch("TAILVIEW_POSTGRES_DB", "tailview_production") %>_cache
    username: <%= ENV.fetch("TAILVIEW_POSTGRES_USER", "tailview_user") %>
    password: <%= ENV.fetch("TAILVIEW_POSTGRES_PASSWORD", "") %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    host: <%= ENV.fetch("TAILVIEW_POSTGRES_HOST", "tailview_postgres") %>
    port: <%= ENV.fetch("TAILVIEW_POSTGRES_PORT", "5432") %>
    database: <%= ENV.fetch("TAILVIEW_POSTGRES_DB", "tailview_production") %>_queue
    username: <%= ENV.fetch("TAILVIEW_POSTGRES_USER", "tailview_user") %>
    password: <%= ENV.fetch("TAILVIEW_POSTGRES_PASSWORD", "") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    host: <%= ENV.fetch("TAILVIEW_POSTGRES_HOST", "tailview_postgres") %>
    port: <%= ENV.fetch("TAILVIEW_POSTGRES_PORT", "5432") %>
    database: <%= ENV.fetch("TAILVIEW_POSTGRES_DB", "tailview_production") %>_cable
    username: <%= ENV.fetch("TAILVIEW_POSTGRES_USER", "tailview_user") %>
    password: <%= ENV.fetch("TAILVIEW_POSTGRES_PASSWORD", "") %>
    migrations_paths: db/cable_migrate
